# Generated by Django 4.1.4 on 2022-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("birth_date", models.DateField()),
                ("age", models.IntegerField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=6)),
                ("mobile_no", models.CharField(max_length=12)),
            ],
        ),
    ]
